version: '3'

services:
  owncloud:
    image: owncloud:latest
    container_name: owncloud
    restart: always
    ports:
      - "8091:80"
    environment:
      - OWNCLOUD_DOMAIN=localhost:8091
      - OWNCLOUD_TRUSTED_DOMAINS=localhost
      - OWNCLOUD_ADMIN_USERNAME=theagentcompany
      - OWNCLOUD_ADMIN_PASSWORD=theagentcompany
    volumes:
      - owncloud_data:/var/www/html/data
      - owncloud_config:/var/www/html/config
    networks:
      - owncloud_network

  collabora:
    image: collabora/code:latest
    container_name: collabora
    restart: always
    ports:
      - "8092:9980"
    environment:
      - domain=localhost:8091
      - extra_params=--o:ssl.enable=false --o:ssl.termination=false --o:net.frame_ancestors=localhost:8091 --o:allowed_languages=zh_CN,en
    cap_add:
      - MKNOD
    networks:
      - owncloud_network

networks:
  owncloud_network:
    driver: bridge

volumes:
  owncloud_data:
  owncloud_config: