

CREATE SEQUENCE event_id_seq INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 NO CYCLE;
CREATE SEQUENCE user_id_seq INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 NO CYCLE;

CREATE TABLE events(id INTEGER DEFAULT(nextval('event_id_seq')) PRIMARY KEY, "name" VARCHAR, date DATE, description VARCHAR);
CREATE TABLE users(id INTEGER DEFAULT(nextval('user_id_seq')) PRIMARY KEY, username VARCHAR, email VARCHAR, "password" VARCHAR);




